name: 'UI Tests'

on: push

jobs:
  # Install and cache npm dependencies
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v1
      - name: Install dependencies if cache invalid
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile
  # Run interaction and accessibility tests
  interaction-and-accessibility:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - name: Restore pnpm dependencies
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v1
      - name: Install MSW
        run: pnpm add msw-storybook-addon
      - name: Run Pre Install Command
        run: pnpm prepare
      - name: Build Storybook
        run: pnpm build-storybook --quiet
      - name: Publish　Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TEAMENVER_PAGES }}
          publish_dir: ./storybook-static
