name: 'UI Tests'

on: push

jobs:
  # Install and cache npm dependencies
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: Cache styled-system
        uses: actions/cache@v3
        id: panda_cache
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}

      - name: Pre dependencies installation
        if: steps.panda_cache.outputs.cache-hit != 'true'
        run: bun run prepare

      - name: Install dependencies if cache invalid
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun i --frozen-lockfile

  check: # This job is for checking the code style and type errors.
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: Restore styled-system
        id: panda_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}

      - name: Run Type Check
        run: bun run check:typecheck # check ts compile error
      - name: Run Lint
        run: bun run check:lint # check code style

  # Build storybook
  build-storybook:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: Restore styled-system
        id: panda_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}

      - name: Cache Storybook
        id: storybook_cache
        uses: actions/cache@v3
        with:
          path: storybook-static
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Run Pre Install Command
        run: bun prepare

      - name: Build Storybook
        run: bun storybook:build --quiet

  # Run interaction and accessibility tests
  test-storybook:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: Restore styled-system
        id: panda_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}

      - name: Restore Storybook
        id: storybook_cache
        uses: actions/cache@v3
        with:
          path: storybook-static
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: Install MSW
        run: bun add msw-storybook-addon

      - name: Serve Storybook and run tests
        run: bun run storybook:ci
